tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "bat"
brew "gh"
brew "zsh"
brew "coreutils"
brew "jq"
brew "yq"
brew "starship"
brew "zoxide"
brew "fzf"
brew "zsh-syntax-highlighting"
brew "gitleaks"
brew "mackup"
brew "zsh-autosuggestions"
brew "node"
brew "wakatime-cli"
brew "go"
brew "exa"
brew "goreleaser/tap/goreleaser"
brew "helm"
brew "kubectl"
brew "git-crypt"
brew "k3d"
brew "kubectx"
brew "tmux"

cask "google-cloud-sdk"
cask "font-hack-nerd-font"
cask "font-fira-code"
cask "brave-browser"
cask "spotify"
cask "signal"
cask "iterm2"
cask "zoom"
cask "vlc"
cask "microsoft-office"
cask "obsidian"

mas "Meeter", id: 1510445899
mas "Microsoft Outlook", id: 985367838
mas "Slack", id: 803453959
mas "Unsplash Wallpapers", id: 1284863847
