tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "goreleaser/tap"
tap "cloudflare/cloudflare"
tap "tomanthony/brews"
tap "knqyf263/pet"

brew "bat"
brew "gh"
brew "zsh"
brew "coreutils"
brew "jq"
brew "yq"
brew "starship"
brew "fzf"
brew "zsh-syntax-highlighting"
brew "gitleaks"
brew "mackup"
brew "zsh-autosuggestions"
brew "wakatime-cli"
brew "upx"
brew "exa"
brew "goreleaser/tap/goreleaser"
brew "helm"
brew "kubectl"
brew "git-crypt"
brew "k3d"
brew "kubectx"
brew "tmux"
brew "golangci-lint"
brew "mas"
brew "go"
brew "mkcert"
brew "mkdocs"
brew "krew"
brew "zoxide"
brew "git"
brew "atuin"
brew "gnupg"
brew "tomanthony/brews/itermocil"
brew "gnu-sed"
brew "gnutls"
brew "glib"
brew "findutils"
brew "wget"
brew "node"
brew "goreleaser"
brew "mage"
brew "knqyf263/pet/pet"
brew "kubernetes-cli"
brew "qemu"
brew "cloudflare/cloudflare/cloudflared"


cask "google-cloud-sdk"
cask "font-hack-nerd-font"
cask "font-fira-code"
cask "spotify"
cask "signal"
cask "iterm2"
cask "zoom"
cask "vlc"
cask "notion"
cask "cron"
cask "whatsapp"
cask "docker"
cask "rectangle"
# cask "stats" # not use currently

mas "Slack", id: 803453959
mas "Unsplash Wallpapers", id: 1284863847
mas "AS Timer", id: 512464723
mas "Gifski", id: 1351639930
