#!/usr/bin/env bash

# Exporting the specific shell we want to work with:

SHELL='/bin/bash'
export SHELL

# Standard dotbot pre-configuration:

readonly DOTBOT_DIR='dotbot'
readonly DOTBOT_BIN='bin/dotbot'
readonly BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

readonly ARGS="$@"

cd "$BASEDIR"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"


"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir dotbot-brewfile -c "${CONFIG}" "${@}"

# Linking dotfiles:

run_dotbot () {
  local CONFIG
  CONFIG="$1"

  "$BASEDIR/$DOTBOT_DIR/$DOTBOT_BIN" \
    -d "${BASEDIR}" \
    --plugin-dir dotbot-brewfile \
    -c "${CONFIG}"
}

run_dotbot 'steps/term-dependencies.yml' || true
if [ "$APPS" = true ]; then
  run_dotbot 'steps/app-dependencies.yml' || true
fi

run_dotbot 'steps/terminal.yml' || true
